// Generated by Website Factory. Update via the factory pipeline, not by hand.

export interface MenuItem {
  name: string;
  native?: string;
  nr?: string;
  description?: string;
  price: string;
  spicy?: boolean;
  vegan?: boolean;
  note?: string;
}

export type MenuCategory = {
  id: string;
  label: string;
  native?: string;
  intro?: string;
  items: MenuItem[];
};

export const menuDataGeneratedFromFactory = true;

export const menuImageUrls: string[] = [
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGdTYkix_op1ntcwYa5GK61CqQMPNnmIHLUuc4S3AFbYwGn2TUijNav8SiS9uJOQbQ72fhzMSKPaXgo0QwNKQcjBaS-68wXhYuxdoUIF9dH624EVDlnYWYa7b79oARuQVnXzaPj=s202-w152-h202-p-k-no",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFeZetov8ASu8iS6oTkk5KPjG5hnzH1jw_ao5tfILFQngs93VrtEjVrcfvZulTLH5GjXCm2ert-sLhZ9gWuRhx88ttHQau_WUBWNJg9gZ2xfsuU1USoyhrABjWpPNTkWiBUJB-h=s202-w152-h202-p-k-no",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHWJvtAQKXLCHs79PZoj_zLf8TW2Jwy9_RiatAfjbv2iHAHNl8-9Wr4VX4OapstywAge1ErB75-ANW2QMMD6PAv0rCHHG1UYCAIEqpPe01qMLKK7lJm2l04I3yaJ3k71WUijgBs=s202-w152-h202-p-k-no",
  "https://lh3.googleusercontent.com/p/AF1QipNJbhBPN7j30DgVcFB-6jwJDAapxCm_GWB_FZau=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEmCuZcHgS5YBtLnkj3sl8INty57W1NyIf99Y2D8k_H4ISggQmNGeq_0UwdYFPe7m2dbcz5KDNty6Ta4lKPm9qQ1gfjvY5xl7YRBFrjJ2JWd2elGcxeWwZuWy_xJC-amsjdi9xDFx84gb8j=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGmivcJGqs2a5tc_4jrZAYt-lPtu1PGJasU51W_3IawNvnjxavsi3X9V7ZMWcigdafu3_EN2X6IWwi6bLQvKz7jiYZi6qIkdLEw_jXkdiwevXv_-SCiqc_iexa3sE26BZFeqdZl=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipPRLoN_JwLjRh2vk07MWd60XJLVKsxYMrBecw5K=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAExcPuB5FDJ0cTRmD4Lpys92ITXV4ENXd0HZyhJF0GtJ9nrKZvbdLJ3ShTNVxFSVwjt6hJRiv7DePEcf8OnsSjIJN-YChElVjXWz3yWLm28lcMpSGxa8dNBZJaLa3M2_mCXc_BiyZAI0_kf=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFIsPPluvS2x0mTwbv656YJg0OHAbVK1m1Adhx3AVguqGImGUEZD8ubX-AJQ7KXHAjdOpA1MZSm9k7Pii4DWEYHwDxHIFO71HaKcRsZ_XJKwzc6Bn12Euazv4AzL-5SiKVtNxoaZcdGIG4=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFUfv13Z_3uwMJxII5FaTxCWMKeDhRg2RlWOZyCfKf_qedItmytpqEhE3fTxhOTVVkuPoYeAoz2nn8A4qmVjq4I-zXXCmXQFAWNXYwGurc4VBVWJUvjIKyvpJu50Qglk8DCZZ6J=w1600-h1200",
  "https://lh3.googleusercontent.com/proxy/Y39oZrfNYFFLfjPRyAOiq73c59xKbNJ8q311DuNPmy0-efnsqOx0vUXrYFYSv5eMlclDLKs7-yaOneQbVZXIGCW2X4FLeIBkwXv9uMQtMyIp6pxF28luGpwgYLiLteqLd7LjLOvEGPt8NkBx8F4pRmsLr0NzjQ=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipN3lfPB3T_IyI7JnbtqyYrPgMM9XSwcGyEEMeIa=w1600-h1200",
  "https://lh3.googleusercontent.com/p/AF1QipNv8diIuLSlmBeh5rv-AxzKt3rlLJY5N6Naf1Bc=w1600-h1200",
  "https://lh6.googleusercontent.com/proxy/VMmzTjOhkzxh87bzCrhEYiXi56Qr2GmgV1GlMK8GKSpuwhqLsqgaaJNhNcmU4USg9OxDytoSfrmCj-egDtr4VTymRMLlKAuHKRw-JMtIuLzwrk6qfWRuSLP9QAB5hiStOUrOsgkTm0m0HveREZLRxeWSp0UMVQ=w1600-h1200",
  "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEBhlwf8NXg6M-1ExgHZXTO8E_vhQB2zMDoJv_xZHvXu4EqGQHA0IXsBNs5hUgqr_rc8H4fssHVCIK0NWMIcFH88Qi4djh1TLuIW8tR2eexPr8A4OaRLnOj8W1OhnYlmagDDL__eCIEKLJf=w1600-h1200"
];

export const menuCategories: MenuCategory[] = [
  {
    "id": "wraps",
    "label": "WRAPS",
    "items": [
      {
        "name": "CLASSIC",
        "description": "HÜHNCHEN / THUNFISCH ODER VEGETARISCH",
        "price": "7,20"
      },
      {
        "name": "EXOTICA",
        "description": "RUCOLA | HÄNCHEN | SCHAFSKÄSE | CURRY-MANGO",
        "price": "8,20"
      },
      {
        "name": "TROPICAL",
        "description": "ANANAS | RUCOLA | HÄNCHEN | AIOLI TOSCANA",
        "price": "8,20"
      },
      {
        "name": "SCHRIMP",
        "description": "RUCOLA | SCHRIMPS | COCTAILSOSSE",
        "price": "8,20"
      },
      {
        "name": "BALKAN",
        "description": "SUCUK | SCHAFSKÄSE | AIOLI",
        "price": "8,20"
      },
      {
        "name": "BEEF",
        "description": "RINDERSTREIFEN | HONIGSENF",
        "price": "8,20"
      },
      {
        "name": "FALAFEL",
        "description": "MIT SESAMSOSSE",
        "price": "7,40"
      }
    ]
  },
  {
    "id": "boreks",
    "label": "BÖREKS",
    "items": [
      {
        "name": "ZIGARRENBÖREK",
        "description": "BLÄTTERTEIGRÖLLCHEN MIT FETAKÄSE",
        "price": "2,50"
      },
      {
        "name": "HACKFLEISCHBÖREK",
        "description": "BLÄTTERTEIG GEFÜLLT MIT RINDERHACK & GEBR. ZWIEBELN",
        "price": "5,00"
      },
      {
        "name": "SPINATBÖREK",
        "description": "BLÄTTERTEIG GEFÜLLT MIT SPINAT & FETAKÄSE",
        "price": "4,50"
      },
      {
        "name": "FETABÖREK",
        "description": "BLÄTTERTEIG MIT FETAKÄSE",
        "price": "4,00"
      },
      {
        "name": "FETABRÖTCHEN",
        "description": "BLÄTTERTEIG MIT FETAKÄSE",
        "price": "3,00"
      }
    ]
  },
  {
    "id": "salate",
    "label": "SALATE",
    "items": [
      {
        "name": "EXOTICA SALAT",
        "description": "GEMISCHTER SALAT (VEGE)",
        "price": "7,50"
      },
      {
        "name": "COUSCOUS SALAT",
        "description": "BULGUR/KISIR (VEGE)",
        "price": "6,90"
      },
      {
        "name": "HÄHNCHEN SALAT",
        "description": "GEMISCHTER SALAT MIT HÄHNCHEN",
        "price": "8,50"
      },
      {
        "name": "THUNFISCH SALAT",
        "description": "GEMISCHTER SALAT MIT THUNFISCH",
        "price": "8,20"
      },
      {
        "name": "TROPICAL SALAT",
        "description": "GEMISCHTER SALAT MIT ANANAS",
        "price": "7,90"
      },
      {
        "name": "SHRIMPS SALAT",
        "description": "GEMISCHTER SALAT MIT SCHRIMPS",
        "price": "8,90"
      },
      {
        "name": "FALAFEL SALAT",
        "description": "GEMISCHTER SALAT MIT FALAFEL",
        "price": "8,40"
      },
      {
        "name": "BEILAGEN SALAT",
        "description": "ZUM BÖREK",
        "price": "5,00"
      }
    ]
  },
  {
    "id": "fruit-boxes",
    "label": "FRUIT BOXES",
    "items": [
      {
        "name": "OBSTSALAT",
        "price": "6,00"
      },
      {
        "name": "ANANAS BOX",
        "price": "4,00"
      },
      {
        "name": "ERDBEER BOX",
        "price": "4,50"
      },
      {
        "name": "FLUG-MANGO BOX",
        "price": "7,00"
      },
      {
        "name": "WASSERMELONEN BOX",
        "price": "4,00"
      },
      {
        "name": "HONIGMELONENBOX",
        "price": "5,00"
      },
      {
        "name": "EXOTICBOX",
        "description": "MANGO | HONIGMELONE | PAPAYA | ANANAS",
        "price": "8,00"
      }
    ]
  },
  {
    "id": "fresh-juices",
    "label": "FRESH JUICES",
    "items": [
      {
        "name": "KAROTTENSAFT",
        "price": "3,00"
      },
      {
        "name": "KAROTTEN MIT INGWER",
        "price": "3,50"
      },
      {
        "name": "APFELSAFT",
        "price": "4,00"
      },
      {
        "name": "ORANGENSAFT",
        "price": "4,00"
      },
      {
        "name": "GRAPEFRUITSAFT",
        "price": "4,50"
      },
      {
        "name": "GARTENSAFT",
        "description": "ROTE BETE | APFEL | KAROTTEN | INGWER",
        "price": "4,50"
      },
      {
        "name": "GRANATAPFELSAFT",
        "description": "MIT ORANGENSAFT",
        "price": "5,50"
      },
      {
        "name": "VITAMIN DRINK",
        "description": "APFEL ODER ORANGENSAFT INGWER | KAROTTE",
        "price": "4,00"
      },
      {
        "name": "EXOTIC DRINK",
        "description": "INGWER | KAROTTE | GRAPEFRUIT",
        "price": "4,50"
      },
      {
        "name": "ANANASMIX",
        "description": "ANANAS | ORANGE",
        "price": "4,00"
      },
      {
        "name": "ERDBEERMIX",
        "description": "ERDBEER | ANANAS | ORANGE",
        "price": "4,00"
      },
      {
        "name": "KIWIMIX",
        "description": "KIWI | ANANAS | ORANGE | ZITRONE | BANANE",
        "price": "4,00"
      },
      {
        "name": "MANGOMIX",
        "description": "MANGO | ANANAS | ORANGE",
        "price": "4,50"
      },
      {
        "name": "MILKMIX",
        "description": "ERDBEER ODER BANANE | MILCH",
        "price": "4,00"
      },
      {
        "name": "TROPICALMIX",
        "description": "MANGO | ANANAS | MILCH",
        "price": "4,50"
      }
    ]
  },
  {
    "id": "bowls",
    "label": "BOWLS",
    "items": [
      {
        "name": "CHICKEN BOWL",
        "price": "11,90"
      },
      {
        "name": "FALAFEL",
        "price": "11,90"
      },
      {
        "name": "BEEF BOWL",
        "price": "12,50"
      },
      {
        "name": "SHRIMP BOWL",
        "price": "12,50"
      },
      {
        "name": "TUNA BOWL",
        "price": "11,50"
      }
    ]
  }
];
