// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "Exotica City",
  "shortName": "Exotica City",
  "tagline": "Italienisch",
  "logoGlyph": "E",
  "cuisine": "Italienisch",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "06221 7271234",
  "phoneLink": "tel:+4962217271234",
  "email": "",
  "address": {
    "street": "Poststraße 12",
    "cityLine": "69115 Heidelberg",
    "city": "Heidelberg"
  },
  "mapsUrl": "https://maps.google.com/?cid=1909569571072030898&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=1909569571072030898&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://www.instagram.com/exotica.hyd/",
    "facebook": "https://www.facebook.com/p/Gourmet-City-Asiatisches-Restaurant-100071101327310",
    "tiktok": "https://tiktok.com/@exoticacity.heidelberg",
    "hidden": {
      "instagram": false,
      "facebook": false,
      "tiktok": true
    },
    "titleHidden": false
  },
  "closedDays": [
    0
  ],
  "closedDaysLabel": "Geschlossen: Sonntag.",
  "hours": [
    {
      "day": "Montag, Dienstag, Mittwoch, Donnerstag & Freitag",
      "time": "09:00–20:00 Uhr",
      "closed": false
    },
    {
      "day": "Samstag",
      "time": "10:00–20:00 Uhr",
      "closed": false
    },
    {
      "day": "Sonntag",
      "time": "Geschlossen",
      "closed": true
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "Exotica City | Italienisch in Heidelberg",
    "description": "Exotica City in Heidelberg. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "keywords": [
      "Exotica City",
      "Italienisch Heidelberg",
      "Exotica City Heidelberg"
    ],
    "ogTitle": "Exotica City",
    "ogDescription": "Exotica City in Heidelberg. italienische Küche, aktuelle Öffnungszeiten und Kontaktinformationen auf einen Blick.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
