// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 4.5,
  "totalRatings": 287,
  "reviews": [
    {
      "author": "Lisa-Marie M.",
      "rating": 5,
      "text": "Kamen zufällig vorbei und sind begeistert. Alles frisch und sehr lecker! Sehr nettes und geduldiges Personal. Vielen Dank",
      "time": "vor 11 Monaten"
    },
    {
      "author": "Zhiar Qassab",
      "rating": 5,
      "text": "Sehr netter, kleiner Imbiss mit tollen Angeboten und frisch zubereitetem Essen. Man kann jeden Handgriff beobachten und steht in ständigem Austausch mit den freundlichen Mitarbeiterinnen. Es gibt kleine Sitzmöglichkeiten, um auch gleich vor Ort seine Mahlzeit zu genießen. Ich hatte dort eine schöne Zeit. Ich kommen gerne wieder. 😍",
      "time": "vor 2 Jahren"
    },
    {
      "author": "Julze",
      "rating": 5,
      "text": "Sehr nette Leute und auch schnell zubereitet. Die Stühle sind etwas unbequem und der Kuskus nicht der alle tollste aber die Preis Leistung macht das wieder gut",
      "time": "vor 2 Jahren"
    },
    {
      "author": "T K",
      "rating": 5,
      "text": "Hier ist alles immer super frisch und super lecker. Ich empfehle den Classic Wrap oder den Hähnchen Salat.",
      "time": "vor 7 Monaten"
    },
    {
      "author": "Nette Nette",
      "rating": 5,
      "text": "Sehr netter, kleiner Imbiss mit tollen Angeboten und frisch zubereitetem Essen. Man kann jeden Handgriff beobachten und steht in ständigem Austausch mit den freundlichen Mitarbeiterinnen. Es gibt kleine Sitzmöglichkeiten, um auch gleich vor Ort seine Mahlzeit zu genießen. Wir hatten dort eine schöne Zeit. Die Wraps waren richtig lecker und wir kommen gerne wieder.  👍",
      "time": "vor 4 Jahren"
    }
  ]
};
